<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" onClick="window.location.reload()" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Modifier <?php echo $projet->getTitre_Projet(); ?> </h4>                
        </div>       
        <br>
        <div class="modal-body">
        <form method="post" action="<?php echo $this->url('projet', array('action' => 'editProjet', 'idprojet' => $projet->getId_projet())); ?>" role="form" class="form-horizontal">
            <div class="form-group">
                <label for="titre_projet" class="col-sm-2">Titre: </label>
                <div class="col-sm-10">
                    <input type="text" name="titre_projet" value="<?php echo $projet->getTitre_projet(); ?>" class="form-control">
                </div>
            </div>                            
            <div class="form-group">
                <label for="description_projet" class="col-sm-2">Description:</label>
                <div class="col-sm-10">
                    <textarea name="description_projet" class="form-control"><?php echo $projet->getDescription_projet(); ?></textarea>
                </div>
            </div>                            
            <div class="form-group">
                <label for="date_debut_projet" class="col-sm-2">Début:</label>
                <div class="col-sm-10">
                    <input type="date" class="form-control" id="date_debut_projet" name="date_debut_projet" data-provide="datepicker" value="<?php echo $projet->getDate_debut_projet()->format('d-m-Y'); ?>"><br>
                </div>    
            </div>                        
            <div class="form-group">
                <label for="date_fin_projet" class="col-sm-2">Fin:</label>
                <div class="col-sm-10">
                    <input type="date" class="form-control" id="date_fin_projet" name="date_fin_projet" data-provide="datepicker" value="<?php echo $projet->getDate_fin_projet()->format('d-m-Y'); ?>"><br>
                </div>
            </div>                            
            <div class="form-group">
                <label for="id_status" class="col-sm-2">Status:</label>
                <div class="col-sm-10">
                    <select name="id_status" class="form-control">
                        <?php
                        foreach ($status as $statu)
                        {
                            if ($projet->getId_status() === $statu->getId_status())
                            {
                                ?>
                                <option value=<?php echo $statu->getId_status() ?> selected="selected"><?php echo $statu->getLibelle_status() ?></option>
                                <?php
                            }
                            else
                            {
                                ?>      
                                <option value=<?php echo $statu->getId_status() ?>><?php echo $statu->getLibelle_status() ?></option>
                                <?php
                            }
                        }
                        ?>                        
                    </select>
                </div>
            </div>       



            <div class="modal-footer">
                <input type="submit" class="btn btn-primary" value="Valider"/>
                <button type="button" class="btn btn-default" onClick="window.location.reload()" data-dismiss="modal">Fermer</button>                
            </div>
        </form>
    </div>

    </div>
</div>

    